import type { YouTubeVideo } from '@/types';

const YOUTUBE_API_BASE = 'https://www.googleapis.com/youtube/v3';

export const isYouTubeConfigured = Boolean(
  import.meta.env.VITE_YOUTUBE_API_KEY
);

/**
 * Search YouTube for real videos using queries generated by Gemini.
 * Falls back gracefully if API key is not configured.
 */
export async function searchYouTubeVideos(
  queries: string[],
  maxResultsPerQuery = 2
): Promise<YouTubeVideo[]> {
  const apiKey = import.meta.env.VITE_YOUTUBE_API_KEY;
  if (!apiKey) return [];

  const allVideos: YouTubeVideo[] = [];
  const seenIds = new Set<string>();

  for (const query of queries.slice(0, 3)) {
    try {
      const params = new URLSearchParams({
        part: 'snippet',
        q: query,
        type: 'video',
        maxResults: String(maxResultsPerQuery),
        relevanceLanguage: 'ko',
        regionCode: 'KR',
        videoCategoryId: '26', // Howto & Style
        key: apiKey,
      });

      const res = await fetch(`${YOUTUBE_API_BASE}/search?${params}`);
      if (!res.ok) {
        if (import.meta.env.DEV) console.warn(`YouTube API search failed for "${query}":`, res.status);
        continue;
      }

      const data = await res.json();
      const items = data.items || [];

      for (const item of items) {
        const videoId = item.id?.videoId;
        if (!videoId || seenIds.has(videoId)) continue;
        seenIds.add(videoId);

        allVideos.push({
          videoId,
          title: item.snippet.title,
          channelTitle: item.snippet.channelTitle,
          thumbnail:
            item.snippet.thumbnails?.high?.url ||
            item.snippet.thumbnails?.medium?.url ||
            item.snippet.thumbnails?.default?.url ||
            '',
          publishedAt: item.snippet.publishedAt,
        });
      }
    } catch (err) {
      if (import.meta.env.DEV) console.warn(`YouTube API error for "${query}":`, err);
    }
  }

  // Fetch video details (viewCount, duration) if we have results
  if (allVideos.length > 0 && apiKey) {
    try {
      const ids = allVideos.map((v) => v.videoId).join(',');
      const params = new URLSearchParams({
        part: 'contentDetails,statistics',
        id: ids,
        key: apiKey,
      });

      const res = await fetch(`${YOUTUBE_API_BASE}/videos?${params}`);
      if (res.ok) {
        const data = await res.json();
        const detailMap = new Map<string, { viewCount?: string; duration?: string }>();
        for (const item of data.items || []) {
          detailMap.set(item.id, {
            viewCount: item.statistics?.viewCount,
            duration: formatDuration(item.contentDetails?.duration),
          });
        }
        for (const video of allVideos) {
          const detail = detailMap.get(video.videoId);
          if (detail) {
            video.viewCount = detail.viewCount;
            video.duration = detail.duration;
          }
        }
      }
    } catch {
      // Non-critical: we already have basic video info
    }
  }

  return allVideos;
}

/** Convert ISO 8601 duration (PT15M33S) to human-readable (15:33) */
function formatDuration(iso?: string): string {
  if (!iso) return '';
  const match = iso.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return '';
  const h = match[1] ? `${match[1]}:` : '';
  const m = match[2] || '0';
  const s = (match[3] || '0').padStart(2, '0');
  return `${h}${m}:${s}`;
}

/** Format view count to human-readable (1.2M, 345K, etc.) */
export function formatViewCount(count?: string): string {
  if (!count) return '';
  const n = parseInt(count, 10);
  if (isNaN(n)) return count;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return String(n);
}

/** Get YouTube video URL from videoId */
export function getYouTubeVideoUrl(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

/** Get YouTube embed URL for potential future embed usage */
export function getYouTubeEmbedUrl(videoId: string): string {
  return `https://www.youtube.com/embed/${videoId}`;
}
