
export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number; // cents (e.g. 4500 = $45.00)
  priceDisplay: string; // formatted (e.g. "$45.00")
  desc: string;
  matchScore: number;
  ingredients: string[];
  safetyRating: string; // e.g., "EWG Green", "Vegan"
  category: 'base' | 'lip' | 'eye' | 'skincare' | 'tool';
  imageUrl?: string;
  melaninRange: [number, number]; // min-max melanin index this product works for
}

/** Lightweight product reference used in AI recommendations */
export interface ProductRecommendation {
  name: string;
  brand: string;
  price: string;
  desc: string;
  matchScore: number;
  ingredients: string[];
  safetyRating: string;
}

export interface VideoRecommendation {
  title: string;
  creator: string;
  views: string;
  duration: string;
  tag: string;
  aiCoaching: string;
  matchPercentage: number;
  skillLevel: string;
}

/** YouTube search hints generated by Gemini for hybrid video curation */
export interface YouTubeSearchHints {
  queries: string[];              // 2-3 Korean YouTube search queries
  focusPoints: string[];          // Key techniques to watch for
  channelSuggestions: string[];   // Recommended Korean beauty channels
}

/** Real YouTube video fetched via YouTube Data API */
export interface YouTubeVideo {
  videoId: string;
  title: string;
  channelTitle: string;
  thumbnail: string;
  publishedAt: string;
  viewCount?: string;
  duration?: string;
}

export interface UserPreferences {
  environment: 'Office' | 'Outdoor' | 'Studio';
  skill: 'Beginner' | 'Intermediate' | 'Pro';
  mood: 'Natural' | 'Elegant' | 'Powerful';
}

export interface AnalysisResult {
  tone: {
    melaninIndex: number; // 1-6
    undertone: 'Warm' | 'Cool' | 'Neutral';
    skinHexCode: string; // e.g. "#C8A98B"
    skinConcerns: string[];
    description: string;
  };
  sherlock: {
    proportions: {
      upper: string;
      middle: string;
      lower: string;
    };
    eyeAngle: string;
    boneStructure: string;
    facialVibe: string;
  };
  kMatch: {
    celebName: string;
    adaptationLogic: {
      base: string;
      lip: string;
      point: string;
    };
    styleExplanation: string;
    aiStylePoints: string[]; // Key takeaways for the card hover
  };
  recommendations: {
    ingredients: string[];
    products: ProductRecommendation[];
    videos: VideoRecommendation[];
    sensitiveSafe: boolean;
  };
  /** AI-generated tags for auto-categorization */
  autoTags?: string[];
  /** YouTube search hints for hybrid curation */
  youtubeSearch?: YouTubeSearchHints;
}


export interface CartItem {
  product: Product;
  quantity: number;
}

export interface Order {
  id: string;
  items: CartItem[];
  subtotal: number;
  shipping: number;
  total: number;
  shippingMethod: 'dhl' | 'ems';
  shippingName?: string;
  shippingCountry?: string;
  shippingAddress?: string;
  status: 'pending' | 'paid' | 'shipped' | 'delivered';
  stripeSessionId?: string;
  createdAt: string;
}

export interface MuseBoard {
  id: string;
  name: string;
  icon: string;
  count: number;
  aiSummary: string;
}

export interface SavedMuse {
  id: string;
  userImage: string;
  celebImage: string;
  celebName: string;
  date: string;
  vibe: string;
  boardId?: string;
  aiStylePoints: string[];
  tags: string[];
  notes: string;
  extraImages: string[];
}
