
export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number; // cents (e.g. 4500 = $45.00)
  priceDisplay: string; // formatted (e.g. "$45.00")
  desc: string;
  matchScore: number;
  ingredients: string[];
  safetyRating: string; // e.g., "EWG Green", "Vegan"
  category: 'base' | 'lip' | 'eye' | 'skincare' | 'tool';
  imageUrl?: string;
  melaninRange: [number, number]; // min-max melanin index this product works for
  affiliate_url?: string | null;
}

/** Lightweight product reference used in AI recommendations */
export interface ProductRecommendation {
  name: string;
  brand: string;
  price: string;
  desc: string;
  matchScore: number;
  ingredients: string[];
  safetyRating: string;
}

export interface VideoRecommendation {
  title: string;
  creator: string;
  views: string;
  duration: string;
  tag: string;
  aiCoaching: string;
  matchPercentage: number;
  skillLevel: string;
}

/** YouTube search hints generated by Gemini for hybrid video curation */
export interface YouTubeSearchHints {
  queries: string[];              // 2-3 Korean YouTube search queries
  focusPoints: string[];          // Key techniques to watch for
  channelSuggestions: string[];   // Recommended Korean beauty channels
}

/** Real YouTube video fetched via YouTube Data API */
export interface YouTubeVideo {
  videoId: string;
  title: string;
  channelTitle: string;
  thumbnail: string;
  publishedAt: string;
  viewCount?: string;
  duration?: string;
}

export interface MetricsShift {
  VW: number;
  CT: number;
  MF: number;
  LS: number;
  HI: number;
}

export interface StyleVersion {
  intensity: 'light' | 'medium' | 'full';
  base: string;
  eyes: string;
  lips: string;
  keyProducts: string[];
  metricsShift: MetricsShift;
}

export interface StyleVersions {
  daily: StyleVersion;
  office: StyleVersion;
  glam: StyleVersion;
}

export interface UserPreferences {
  environment: 'Office' | 'Outdoor' | 'Studio';
  skill: 'Beginner' | 'Intermediate' | 'Pro';
  mood: 'Natural' | 'Elegant' | 'Powerful';
}

export interface SkinProfile {
  melaninIndex: number;
  undertone: 'Warm' | 'Cool' | 'Neutral';
  skinHexCode: string;
  skinConcerns: string[];
  description: string;
  skinType?: 'dry' | 'oily' | 'combination' | 'normal';
  sensitivityLevel?: number;
  moistureLevel?: 'low' | 'medium' | 'high';
  sebumLevel?: 'low' | 'medium' | 'high';
  poreSize?: 'small' | 'medium' | 'large';
  skinThickness?: 'thin' | 'medium' | 'thick';
}

export interface AnalysisResult {
  tone: SkinProfile;
  sherlock: {
    proportions: {
      upper: string;
      middle: string;
      lower: string;
    };
    eyeAngle: string;
    boneStructure: string;
    facialVibe: string;
  };
  kMatch: {
    celebName: string;
    adaptationLogic: {
      base: string;
      lip: string;
      point: string;
    };
    styleExplanation: string;
    aiStylePoints: string[]; // Key takeaways for the card hover
  };
  recommendations: {
    ingredients: string[];
    products: ProductRecommendation[];
    videos: VideoRecommendation[];
    sensitiveSafe: boolean;
  };
  /** 5 Metrics facial analysis system */
  fiveMetrics?: FiveMetrics;
  /** AI-generated tags for auto-categorization */
  autoTags?: string[];
  /** YouTube search hints for hybrid curation */
  youtubeSearch?: YouTubeSearchHints;
  /** Daily/Office/Glam style versions */
  styleVersions?: StyleVersions;
}

export interface FiveMetrics {
  visualWeight: {
    score: number;
    eyeWeight: number;
    lipWeight: number;
    noseWeight: number;
    interpretation: string;
  };
  canthalTilt: {
    angleDegrees: number;
    classification: string;
    symmetry: string;
  };
  midfaceRatio: {
    ratioPercent: number;
    philtrumRelative: string;
    youthScore: number;
  };
  luminosity: {
    current: number;
    potential: number;
    textureGrade: string;
  };
  harmonyIndex: {
    overall: number;
    symmetryScore: number;
    optimalBalance: string;
  };
}


export interface CartItem {
  product: Product;
  quantity: number;
}

export interface Order {
  id: string;
  items: CartItem[];
  subtotal: number;
  shipping: number;
  total: number;
  shippingMethod: 'dhl' | 'ems';
  shippingName?: string;
  shippingCountry?: string;
  shippingAddress?: string;
  status: 'pending' | 'paid' | 'shipped' | 'delivered';
  stripeSessionId?: string;
  createdAt: string;
}

export interface MuseBoard {
  id: string;
  name: string;
  icon: string;
  count: number;
  aiSummary: string;
}

export type MuseType = 'analysis' | 'image' | 'url';

export interface SavedMuse {
  id: string;
  type: MuseType;
  image: string;          // primary display image (base64 or URL)
  title?: string;         // user-editable title
  sourceUrl?: string;     // original URL for 'url' type muses
  userImage?: string;     // selfie — only for 'analysis' type
  celebImage?: string;    // celeb reference — only for 'analysis' type
  celebName?: string;     // celeb name — only for 'analysis' type
  date: string;
  vibe?: string;          // facial vibe — only for 'analysis' type
  boardId?: string;
  aiStylePoints?: string[];  // AI style points — only for 'analysis' type
  tags: string[];
  notes: string;
  extraImages: string[];
}
